######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 27 18:56:30 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += grabber.hpp plane.hpp weather_day.hpp parser.hpp
SOURCES += grabber.cpp main.cpp plane.cpp parser.cpp
LIBS += -lcurl
QMAKE_CXXFLAGS += -std=c++11 -g
