######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 27 18:56:30 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += grabber.hpp plane.hpp
SOURCES += grabber.cpp main.cpp plane.cpp
LIBS += -lcurl
