######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 27 18:44:14 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += plane.hpp
SOURCES += main.cpp plane.cpp
